name: Build, test, and publish main as snapshot

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: './.github/workflows/reusable-build-publish.yml'
    with:
      publish: true
    secrets:
      signing_key: ${{ secrets.GPG_SIGNING_KEY }}
      signing_pass: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      publish_user: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
      publish_pass: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}

